# Constants
IMG_SIZE = 60
ROWS, COLS = 8, 8
SQUARE_SIZE = 60
WIDTH, HEIGHT = IMG_SIZE*ROWS*1.6, IMG_SIZE*COLS
CHESSBOARD_WIDTH = SQUARE_SIZE*ROWS
CHESSBOARD_HEIGHT = SQUARE_SIZE*COLS

CHESSBOARD_SQUARES_POS = [(a * SQUARE_SIZE, b * SQUARE_SIZE) for a in range(ROWS) for b in range(COLS)]
